### ISSUE TITLE
Should I envelope?

### ISSUE THREAD

**Issue by alande-amorim** [adnan-kamili/rest-api-response-format#2]
Hey, nice work you've done there.
I've been doing some researching lately and I haven't come across with any conclusive answer regarding whether or not enveloping response data should be done. 
My doubt is regarding this bit:

2- GET - Get item list - HTTP Response Code: **200**
```javascript
    HTTP/1.1 200
    Pagination-Count: 100
    Pagination-Page: 5
    Pagination-Limit: 20
    Content-Type: application/json
    
    [
      {
        "id": 10,
        "name": "shirt",
        "color": "red",
        "price": "$123"
      },
      {
        "id": 11,
        "name": "coat",
        "color": "black",
        "price": "$2300"
      }
    ]
```

Since you've might have been through this road some time ago chances are you've already made your mind.
Some argue that one [do not need to envelop your data](https://stackoverflow.com/a/9999335/1481559) bcause HTTP is your envelope and it should suffice.

While others [firmly state you should](https://stackoverflow.com/a/25930584/1481559).
There are some arguments why you should implement envelopes:
- ~~Pagination~~ [RFC5988 gets you covered](http://tools.ietf.org/html/rfc5988#page-6)
- Weak HTTP Clients (not my case)
- **Security reasons**

[This guy](https://haacked.com/archive/2008/11/20/anatomy-of-a-subtle-json-vulnerability.aspx/) even points out to a [JSON Hijacking](https://www.owasp.org/index.php/AJAX_Security_Cheat_Sheet#Protect_against_JSON_Hijacking_for_Older_Browsers) vulnerability that is solved simply by enveloping his data. [Another guy](https://medium.com/studioarmix/learn-restful-api-design-ideals-c5ec915a430f) initialy stated that it wasn't necessary but changed his mind regarding this issue for the sake of security.

One might think It seems like JSON Hijacking is not a thing anymore but [this guy](http://blog.portswigger.net/2016/11/json-hijacking-for-modern-web.html) points out to a new version of it in modern browsers.

One suggestion is [no envelope by default](https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api):
> We can future proof the API by staying envelope free by default and enveloping only in exceptional cases.

[This guy makes a good point](https://www.reddit.com/r/programming/comments/6edt2t/consistent_and_beautiful_restful_api_design_tips/didbt9d/):
> When a server gets a request with valid auth, it has to be able to trust the client with the response. If a browser allows that response to get leaked to third parties, then that browser is not trust-worthy.

I really can't decide.
What are you thoughts?

**Comment by adnan-kamili** [comment]
Hi,

I also did a lot of research in this matter, analyzed the api responses of some big companies and decided upon no-envelop format. You have already covered most of the points in favour of using no-envelop format.

Additional it looks more intuitive. You should always question if something extra is being added, and if it's not worth, then no point of adding it.

Also the responses can be directly mapped to objects, though not a big deal.
